"""Update quiz_session model

Revision ID: 4a17ce5338d6
Revises: a387ac82c5e9
Create Date: 2025-01-23 01:34:46.192418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a17ce5338d6'
down_revision = 'a387ac82c5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_attempt', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'quiz_session', ['quiz_session_id'], ['id'])

    with op.batch_alter_table('quiz_category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('quiz_difficulty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_index('level')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('level')

    with op.batch_alter_table('quiz_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.drop_index('description')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('description', ['description'], unique=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('quiz_difficulty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('level', ['level'], unique=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('quiz_category', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('question_attempt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
